name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  get_it: ^7.6.8
  via:
    path: ../via/

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.0.0
  via_generator:
    path: ../via_generator/
