version: 38
jobs:
- name: Build Apps
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: docker buildbox
    image: docker-apps-build-box
    args: make build-ci
    envVars:
    - name: GRADLE_OPTS
      value: -Dorg.gradle.unsafe.disable.watch-fs=true
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
