version: 40
jobs:
- name: run tests
  jobExecutor: barebones-mini
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        flutter precache --force
        make ci-test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: fastlane match
  jobExecutor: barebones-mini
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: fastlane match
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        make fastlane-match
    envVars:
    - name: BLOKADA_APPSTORE_KEY_BASE64
      value: '@secret:BLOKADA_APPSTORE_KEY_BASE64@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: pull github
  jobExecutor: barebones-mini
  steps:
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/blokadaorg/blokada.git
    accessTokenSecret: GITHUB_ACCESS
    refs: refs/heads/main refs/heds/25* refs/tags/*
    withLfs: false
    force: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 * 7-19 ? * MON-FRI
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
