version: 38
jobs:
- name: build-android
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: build aab's
    image: docker-apps-build-box
    args: make ci-build-android
    envVars:
    - name: GRADLE_OPTS
      value: -Dorg.gradle.unsafe.disable.watch-fs=true -Dorg.gradle.vfs.watch=false
    - name: BLOKADA_KEY_PWD
      value: '@secret:BLOKADA_KEY_PWD@'
    - name: BLOKADA_KEYSTORE_PWD
      value: '@secret:BLOKADA_KEYSTORE_PWD@'
    - name: BLOKADA_KEYSTORE_BASE64
      value: '@secret:BLOKADA_KEYSTORE_BASE64@'
    - name: BLOKADA_VERSION_NAME
      value: '@tag@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: export artifacts
    artifacts: android/app/build/outputs/bundle/**
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: publish-android
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: publish android family
    image: docker-apps-build-box
    args: make publish-android
    envVars:
    - name: BLOKADA_GPLAY_KEY_BASE64
      value: '@secret:BLOKADA_GPLAY_KEY_BASE64@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: publish android v6
    image: docker-apps-build-box
    args: make publish-android PUBLISH_PKG=org.blokada.sex PUBLISH_AAB=android/app/build/outputs/bundle/sixRelease/app-six-release.aab
    envVars:
    - name: BLOKADA_GPLAY_KEY_BASE64
      value: '@secret:BLOKADA_GPLAY_KEY_BASE64@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    branches: main
  jobDependencies:
  - jobName: build-android
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: test
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: docker test
    image: docker-apps-build-box
    args: make test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
