version: 38
jobs:
- name: publish android manually
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: publish android
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        make publish-android FLAVOR=@param:flavor@
    envVars:
    - name: BLOKADA_GPLAY_KEY_BASE64
      value: '@secret:BLOKADA_GPLAY_KEY_BASE64@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: version-name
    allowEmpty: false
    multiline: false
    pattern: \b\d+\.\d+\.\d+\b
  - !TextParam
    name: flavor
    allowEmpty: false
    multiline: false
    pattern: (family|six)
  jobDependencies:
  - jobName: build android
    requireSuccessful: true
    paramMatrix:
    - secret: false
      valuesProvider: !PassthroughValues
        paramName: version-name
      name: version-name
    - secret: false
      valuesProvider: !PassthroughValues
        paramName: flavor
      name: flavor
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: publish android-six on tag
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: publish android six
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        make publish-android FLAVOR=six
    envVars:
    - name: BLOKADA_GPLAY_KEY_BASE64
      value: '@secret:BLOKADA_GPLAY_KEY_BASE64@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    tags: '*/six/android'
  - !TagCreateTrigger
    tags: '*/six'
  jobDependencies:
  - jobName: build all android
    requireSuccessful: true
    paramMatrix:
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '@tag@'
      name: version-name
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: run tests
  jobExecutor: agent
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        make test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: build android
  jobExecutor: agent
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build aab
    runInContainer: false
    image: docker-apps-build-box
    interpreter: !DefaultInterpreter
      commands: |
        if [ "@param:flavor@" = "family" ]; then
            make ci-build-android-family
        else
            make ci-build-android-six
        fi
    envVars:
    - name: BLOKADA_KEY_PWD
      value: '@secret:BLOKADA_KEY_PWD@'
    - name: BLOKADA_KEYSTORE_PWD
      value: '@secret:BLOKADA_KEYSTORE_PWD@'
    - name: BLOKADA_KEYSTORE_BASE64
      value: '@secret:BLOKADA_KEYSTORE_BASE64@'
    - name: BLOKADA_VERSION_CODE
      value: '@build_number@'
    - name: BLOKADA_VERSION_NAME
      value: '@param:version-name@'
    - name: GRADLE_OPTS
      value: -Dorg.gradle.unsafe.disable.watch-fs=true -Dorg.gradle.vfs.watch=false
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: export artifacts
    artifacts: android/app/build/outputs/bundle/**
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: version-name
    allowEmpty: false
    multiline: false
  - !TextParam
    name: flavor
    allowEmpty: false
    multiline: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: publish android-family on tag
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: publish android-family
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        make publish-android FLAVOR=family
    envVars:
    - name: BLOKADA_GPLAY_KEY_BASE64
      value: '@secret:BLOKADA_GPLAY_KEY_BASE64@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    tags: '*/family/android'
  - !TagCreateTrigger
    tags: '*/family'
  jobDependencies:
  - jobName: build all android
    requireSuccessful: true
    paramMatrix:
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '@tag@'
      name: version-name
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: build all android
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build aab
    runInContainer: false
    image: docker-apps-build-box
    interpreter: !DefaultInterpreter
      commands: |
        make ci-build-android-family ci-build-android-six
    envVars:
    - name: BLOKADA_KEY_PWD
      value: '@secret:BLOKADA_KEY_PWD@'
    - name: BLOKADA_KEYSTORE_PWD
      value: '@secret:BLOKADA_KEYSTORE_PWD@'
    - name: BLOKADA_KEYSTORE_BASE64
      value: '@secret:BLOKADA_KEYSTORE_BASE64@'
    - name: BLOKADA_VERSION_CODE
      value: '@build_number@'
    - name: BLOKADA_VERSION_NAME
      value: '@param:version-name@'
    - name: GRADLE_OPTS
      value: -Dorg.gradle.unsafe.disable.watch-fs=true -Dorg.gradle.vfs.watch=false
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: export artifacts
    artifacts: android/app/build/outputs/bundle/**
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: version-name
    allowEmpty: false
    multiline: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: build ios
  jobExecutor: agent
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build ipa
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        if [ "@param:flavor@" = "family" ]; then
            make ci-build-ios-family
        else
            make ci-build-ios-six
        fi
    envVars:
    - name: BLOKADA_VERSION_CODE
      value: '@build_number@'
    - name: BLOKADA_VERSION_NAME
      value: '@param:version-name@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: export artifacts
    artifacts: ios/*.ipa
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: version-name
    allowEmpty: false
    multiline: false
  - !TextParam
    name: flavor
    allowEmpty: false
    multiline: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: publish ios-family on tag
  jobExecutor: agent
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: publish ipa family
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        make publish-ios FLAVOR=family
    envVars:
    - name: BLOKADA_APPSTORE_KEY_BASE64
      value: '@secret:BLOKADA_APPSTORE_KEY_BASE64@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    tags: '*/family/ios'
  - !TagCreateTrigger
    tags: '*/family'
  jobDependencies:
  - jobName: build ios
    requireSuccessful: true
    paramMatrix:
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '@tag@'
      name: version-name
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - family
      name: flavor
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: publish ios-six on tag
  jobExecutor: agent
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: publish ipa six
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        make publish-ios FLAVOR=six
    envVars:
    - name: BLOKADA_APPSTORE_KEY_BASE64
      value: '@secret:BLOKADA_APPSTORE_KEY_BASE64@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    tags: '*/six/ios'
  - !TagCreateTrigger
    tags: '*/six'
  jobDependencies:
  - jobName: build ios
    requireSuccessful: true
    paramMatrix:
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '@tag@'
      name: version-name
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - six
      name: flavor
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: publish ios manually
  jobExecutor: agent
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: publish ios
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        make publish-ios FLAVOR=@param:flavor@
    envVars:
    - name: BLOKADA_APPSTORE_KEY_BASE64
      value: '@secret:BLOKADA_APPSTORE_KEY_BASE64@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: version-name
    allowEmpty: false
    multiline: false
    pattern: \b\d+\.\d+\.\d+\b
  - !TextParam
    name: flavor
    allowEmpty: false
    multiline: false
    pattern: (family|six)
  jobDependencies:
  - jobName: build ios
    requireSuccessful: true
    paramMatrix:
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '@param:version-name@'
      name: version-name
    - secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '@param:flavor@'
      name: flavor
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
