name: Blokada 6 common module (CI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: |
          git config --global url."https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com".insteadOf "git@github.com"
          flutter pub get

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: make gen build

      - name: Run tests
        run: make test
