targets:
  $default:
    builders:
      via_generator|inject:
        enabled: true
      via_generator|context:
        enabled: true

builders:
  via:
    import: 'package:via_generator/builder.dart'
    builder_factories: ['inject']
    build_extensions: { '.dart': ['.g.dart'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
