name: via_generator
description: A novel DI + visual tracing tool
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  source_gen: ^1.0.0
  via:
    path: ../via/

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.0.0
