#!/usr/bin/env python3
"""Force the iOS deployment target of the generated add-to-app module Podfile.

Why this exists:
  Xcode 27 refuses any pod whose IPHONEOS_DEPLOYMENT_TARGET is below 15.0
  ("the range of supported deployment target versions is 15.0 to 27.0.x").
  Flutter's module template generates `.ios/Podfile` with `platform :ios, '13.0'`,
  and several plugins hardcode 12.0/13.0 in their own podspecs (adapty_flutter,
  the *_privacy resource bundles of path_provider / sqflite / shared_preferences,
  plus the Flutter/FlutterPluginRegistrant pods). CocoaPods honours a podspec's
  own target over the Podfile's `platform` line, so bumping `platform` alone is
  NOT enough — the build still fails. A post_install hook that force-sets every
  pod target's IPHONEOS_DEPLOYMENT_TARGET is the only version-independent fix.

  `.ios/` is gitignored and regenerated by `flutter pub get` whenever absent
  (fresh clone, CI), which resets the Podfile back to 13.0. So this runs on every
  build, before `flutter build swift-package` triggers `pod install`.

The operation is idempotent: running it twice is a no-op.
"""

import re
import sys
from pathlib import Path

MIN_TARGET = "15.0"
MARKER = "# blokada: pin deployment target for Xcode 27 (see patch-podfile-deployment-target.py)"

# Injected inside the existing `installer.pods_project.targets.each do |target|`
# loop that the Flutter module Podfile template already ships.
INJECT = f"""    {MARKER}
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '{MIN_TARGET}'
    end
"""


def main() -> int:
    podfile = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".ios/Podfile")
    if not podfile.exists():
        print(f"[patch-podfile] {podfile} not found — run `flutter pub get` first", file=sys.stderr)
        return 1

    text = podfile.read_text()
    original = text

    # 1) Bump the `platform :ios, 'X'` default line to at least MIN_TARGET.
    text = re.sub(r"platform :ios, '[\d.]+'", f"platform :ios, '{MIN_TARGET}'", text, count=1)

    # 2) Inject the per-target override into the post_install loop (once).
    if MARKER not in text:
        anchor = "    flutter_additional_ios_build_settings(target)\n"
        if anchor not in text:
            print(
                "[patch-podfile] expected `flutter_additional_ios_build_settings(target)` "
                "in post_install loop but did not find it; Flutter template may have changed",
                file=sys.stderr,
            )
            return 1
        text = text.replace(anchor, anchor + INJECT, 1)

    if text != original:
        podfile.write_text(text)
        print(f"[patch-podfile] pinned {podfile} deployment target to {MIN_TARGET}")
    else:
        print(f"[patch-podfile] {podfile} already pinned to {MIN_TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
