# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Six: Push a new beta build to TestFlight"
  lane :six_beta do
    # increment_build_number(build_number: number_of_commits)
    build_app(workspace: "IOS.xcworkspace", scheme: "Prod")
    upload_to_testflight
  end

  desc "Family: Push a new beta build to TestFlight"
  lane :family_beta do
    build_app(workspace: "IOS.xcworkspace", scheme: "FamilyProd")
    upload_to_testflight
  end
end
