name: six-ios family 

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest


    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Manually install FVM and add it to PATH
      - name: Install FVM
        run: |
          flutter pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Verify FVM installation
        run: fvm --version

      - name: Build common lib
        run: |
          git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com/".insteadOf "git@github.com:"
          make sixcommon
 
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
 
      - name: Build & test binary
        run: make family
