name: Blokada 6 for Android (CI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  main_project_module: app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Build common lib
        run: |
          git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com/".insteadOf "git@github.com:"
          make sixcommon

      - name: Build app
        run: make apk

      - name: Run tests
        run: make test
