// import 'package:common/platform/journal/json.dart';
//
// const fixtureJournalEndpoint = '''{"activity":
// [
//    {
//       "device_name":"deviceName",
//       "domain_name":"star.c10r.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:36.973Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:50:33.33Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:50:33.327Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"sentry.io",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:25.958Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"sentry.io",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:25.957Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"e673.dscx.akamaiedge.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.707Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"amp-api-edge.apps.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.68Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"amp-api-edge.apps.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.68Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"amp-api-edge.apps.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.679Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"safebrowsing-proxy.g.aaplimg.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.455Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"proxy.safebrowsing.apple",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.43Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"proxy.safebrowsing.apple",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.43Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"proxy.safebrowsing.apple",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.429Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firebaseremoteconfig.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.187Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firebaseremoteconfig.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.187Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firebaseremoteconfig.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.187Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"mask.apple-dns.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.171Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"mask.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.162Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"mask.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.161Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:50:19.158Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"mask.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.149Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"a1914.dscapi9.akamai.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19.032Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"mzstorekit.itunes.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"mzstorekit.itunes.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:19Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"mzstorekit.itunes.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.999Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"ocsp2.g.aaplimg.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.865Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"ocsp2.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.843Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"ocsp2.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.843Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"ocsp2.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.842Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"kvinit-prod.api.kochava.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.778Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"kvinit-prod.api.kochava.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.778Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"kvinit-prod.api.kochava.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.777Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"control.kochava.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:50:18.674Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"control.kochava.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:50:18.674Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"control.kochava.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:50:18.673Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firebaselogging-pa.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.591Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firebaselogging-pa.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.588Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firebaselogging-pa.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.584Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"pl-pl.fitatu.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.568Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"pki-goog.l.google.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.393Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"ocsp.pki.goog",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.369Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"ocsp.pki.goog",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.368Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"pl-pl.fitatu.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.367Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"ocsp.pki.goog",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.363Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"pl-pl.fitatu.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.363Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"buy.itunes-apple.com.akadns.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.33Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"buy.itunes-apple.com.akadns.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.329Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"inappcheck.itunes.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.304Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"inappcheck.itunes.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.301Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"inappcheck.itunes.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.3Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"star.fallback.c10r.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.295Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"star.fallback.c10r.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.29Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"star.c10r.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.262Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"securetoken.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.26Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"star.c10r.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.256Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"star.c10r.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.255Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firestore.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.254Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firestore.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.254Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"firestore.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.253Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"securetoken.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.25Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"securetoken.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:18.249Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:50:17.949Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"www.google.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:17.949Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:50:17.949Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"e10499.dsce9.akamaiedge.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:15.097Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"configuration.ls.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:15.061Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"configuration.ls.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:15.059Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"configuration.ls.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:50:15.058Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"gateway.fe.apple-dns.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:46:01.816Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"gateway.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:46:01.793Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"gateway.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:46:01.789Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"gateway.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:46:01.789Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"content.fe.apple-dns.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:57.074Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"p31-content.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:57.056Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"p31-content.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:57.051Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"p31-content.icloud.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:57.051Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"edge-075.deber3.ce.apple-dns.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:56.711Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"edge-075.deber3.icloud-content.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:56.685Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"edge-075.deber3.icloud-content.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:56.684Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"edge-075.deber3.icloud-content.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:56.683Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"www.google.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:55.975Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"gateway.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:55.974Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"www.google.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:55.973Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"edge-mqtt.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:55.973Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"gateway.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:55.968Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"edge-mqtt.facebook.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:45:55.968Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"a1931.dscgi3.akamai.net",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:33.74Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"iphone-ld.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:33.688Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"iphone-ld.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:33.688Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"iphone-ld.apple.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:33.688Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"s.youtube.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:14.683Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"s.youtube.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:14.683Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"s.youtube.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:14.682Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"youtubei.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:14.646Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"youtubei.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:14.645Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"youtubei.googleapis.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:14.645Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:41:14.639Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"www.google.com",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:41:14.638Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:41:14.638Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:38:42.971Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"app-measurement.com",
//       "action":"block",
//       "list":"61d55fc2232c79435f05b67c3657aaa0",
//       "timestamp":"2023-05-05T05:38:42.971Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"latency.discord.media",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:38:41.463Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"latency.discord.media",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:38:41.463Z"
//    },
//    {
//       "device_name":"deviceName",
//       "domain_name":"latency.discord.media",
//       "action":"fallthrough",
//       "list":"",
//       "timestamp":"2023-05-05T05:38:41.462Z"
//    }
// ]
// }''';
//
// final fixtureJournalEntries = [
//   JsonJournalEntry(
//       deviceName: "deviceName",
//       domainName: "latency.discord.media",
//       action: "fallthrough",
//       list: "",
//       timestamp: "2023-05-05T05:36:41.462Z"),
//   JsonJournalEntry(
//       deviceName: "deviceName",
//       domainName: "latency.discord.media",
//       action: "fallthrough",
//       list: "",
//       timestamp: "2023-05-05T05:38:41.462Z"),
//   JsonJournalEntry(
//       deviceName: "deviceName",
//       domainName: "latency.discord.media",
//       action: "fallthrough",
//       list: "",
//       timestamp: "2023-05-05T05:38:41.463Z"),
//   JsonJournalEntry(
//       deviceName: "deviceName",
//       domainName: "latency.discord.media",
//       action: "fallthrough",
//       list: "",
//       timestamp: "2023-05-05T05:38:41.464Z"),
//   JsonJournalEntry(
//       deviceName: "deviceName",
//       domainName: "app-measurement.com",
//       action: "block",
//       list: "61d55fc2232c79435f05b67c3657aaa0",
//       timestamp: "2023-05-05T05:38:42.971Z"),
//   JsonJournalEntry(
//       deviceName: "deviceName",
//       domainName: "app-measurement.com",
//       action: "block",
//       list: "61d55fc2232c79435f05b67c3657aaa0",
//       timestamp: "2023-05-05T05:38:42.971Z"),
//   JsonJournalEntry(
//       deviceName: "deviceName",
//       domainName: "app-measurement.com",
//       action: "block",
//       list: "61d55fc2232c79435f05b67c3657aaa0",
//       timestamp: "2023-05-05T05:41:14.638Z"),
// ];
