name: Blokada 6 for Android (Publish)

on:
  push:
    tags:
      - android.v6.**
  workflow_dispatch:

env:
  main_project_module: app
  playstore_name: org.blokada.sex

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./six-android

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build flutter common module
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./six-android/six-common
      - run: flutter build aar --release
        working-directory: ./six-android/six-common
      - run: mkdir -p ../app/six-common/
        working-directory: ./six-android/six-common
      - run: cp -r build/host/outputs/repo ../app/six-common/
        working-directory: ./six-android/six-common

      - name: Build wireguard module
        run: chmod +x ./gradlew
        working-directory: ./wireguard-android
      - run: ./gradlew tunnel:build
        working-directory: ./wireguard-android
      - run: mkdir -p ../app/wireguard-android/lib
        working-directory: ./wireguard-android
      - run: cp tunnel/build/outputs/aar/tunnel-release.aar ../app/wireguard-android/lib/wg-tunnel.aar
        working-directory: ./wireguard-android

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build AAB
        run: ./gradlew app:bundleSixRelease

      - name: Sign app AAB
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: six-android/app/build/outputs/bundle/sixRelease
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.blokada.sex
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: internal
          status: completed
          whatsNewDirectory: six-android/whatsnew
