name: Blokada 5 for Android (Publish)

on:
  workflow_dispatch:
  push:
    tags:
      - android.v5.**

env:
  main_project_module: app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./five-android

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set tag name var
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build apk (five)
        run: ./gradlew assembleFiveRelease

      - name: Sign apk (five)
        uses: r0adkll/sign-android-release@v1
        id: sign_app_five
        with:
          releaseDirectory: five-android/app/build/outputs/apk/five/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_V5 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD_V5 }}
          keyPassword: ${{ secrets.KEY_PASSWORD_V5 }}

      - name: Rename artifact (five)
        run: mv ${{steps.sign_app_five.outputs.signedReleaseFile}} blokada5-${{ steps.vars.outputs.tag }}.apk

      -  name: Upload artifact (five)
         uses: actions/upload-artifact@v3
         with:
           name: blokada5-${{ steps.vars.outputs.tag }}
           path: blokada5-${{ steps.vars.outputs.tag }}.apk

      - name: Publish artifact (five)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: 'Changelog: https://go.blokada.org/changelog'
          files: blokada5-${{ steps.vars.outputs.tag }}.apk


      #- name: Build apk (escaped)
      #  run: ./gradlew assembleEscapedRelease

      #- name: Build apk (google)
      #  run: ./gradlew assembleGoogleslimRelease

