name: Update blocklists mirror (Publish)

on:
  workflow_dispatch:
  push:
    tags:
      - android.v6.**
      - ios.v6.**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./landing-github-pages

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update translations
        run: ./sync-translations.sh

      - name: Update mirrors
        run: cd ./scripts/ && ./mirror.py

