name: Update blocklists mirror (Publish)

on:
  workflow_dispatch:
  push:
    tags:
      - android.v6.**
      - ios.v6.**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout master on landing-github-pages
        run: cd ./landing-github-pages && git checkout master && cd ../

      - name: Update translations
        run: ./sync-translations.sh

      - name: 'Push translations commit'
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './landing-github-pages'
          message: 'sync: translations'
          pull: 'origin'
          push: true

      - name: Update mirrors
        run: cd ./scripts/ && ./mirror.py

      - name: 'Push mirrors commit'
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './landing-github-pages'
          message: 'sync: mirrors'
          push: true

      - name: 'Push submodule to blokada main repo'
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './landing-github-pages'
          message: 'publish mirrors'
          push: true
