name: Update blocklists mirror (Publish)

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.MIRROR_TOKEN }}
          ref: 'main'

      - name: Checkout master on landing-github-pages
        run: cd ./landing-github-pages && git checkout master && cd ../

      - name: Update translations
        run: cd ./landing-github-pages && ./sync-translations.sh && cd ../

      - name: 'Push translations commit'
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './landing-github-pages'
          message: 'sync: translations'
          github_token: ${{ secrets.MIRROR_TOKEN }}
          pull: 'origin'
          push: true

      - name: Update mirrors
        run: cd ./landing-github-pages/scripts/ && ./mirror.py && cd ../

      - name: 'Push mirrors commit'
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './landing-github-pages'
          message: 'sync: mirrors'
          github_token: ${{ secrets.MIRROR_TOKEN }}
          push: true

      - name: 'Push submodule to blokada main repo'
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './'
          message: 'publish mirrors'
          github_token: ${{ secrets.MIRROR_TOKEN }}
          push: true
